### ISSUE TITLE
data samples

### ISSUE THREAD

**Issue by bigsheeper** [zilliztech/infini-client#14]
- "num of points size" is Ambiguous, I suggest "data samples"
![Screenshot from 2020-04-26 15-23-24](https://user-images.githubusercontent.com/42060877/80300846-9885aa00-87d2-11ea-9400-b0b29fd96a75.png)

- The max data samples should not be hard code, it should be the query result of "SELECT COUNT(*) FROM TABLE"

**Comment by talentAN** [comment]
> * "num of points size" is Ambiguous, I suggest "data samples"
>   ![Screenshot from 2020-04-26 15-23-24](https://user-images.githubusercontent.com/42060877/80300846-9885aa00-87d2-11ea-9400-b0b29fd96a75.png)
> * The max data samples should not be hard code, it should be the query result of "SELECT COUNT(*) FROM TABLE"

good suggesion, done ~
